#!/usr/bin/env ruby

require File.expand_path('../../config/boot',        __FILE__)
require File.expand_path('../../config/environment', __FILE__)
require File.expand_path('../../lib/replication_queue', __FILE__)

ReplicationQueue.consume
